### ISSUE TITLE
GitHub status 

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#288] opened 2019-02-25 17:20 UTC
The status page has been deprecated move to the new page https://status.github.com/messages

Posted by: [PeeHaa](https://stackoverflow.com/users/508666)
Source: http://chat.stackoverflow.com/transcript/message/45459825#45459825

**Comment by PeeHaa** [comment] 2019-02-25 17:21
Dupe of https://github.com/Room-11/Jeeves/issues/287

**Closed by PeeHaa** 2019-02-25 17:21 UTC
