### ISSUE TITLE
Feature request: !!tell <user> <command> [...args] command to invoke any command, replying to <user>'s latest message.

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#175] opened 2017-03-01 11:37 UTC
Source - http://chat.stackoverflow.com/transcript/message/35895616#35895616

**Comment by MadaraUchiha** [comment] 2017-03-01 11:38
Eg. `!!tell @HelpVamp canon errors` or `!!tell Gordon dad`.

**Comment by DaveRandom** [comment] 2017-03-03 10:06
Dependent on #179

**Comment by DaveRandom** [comment] 2017-03-03 12:32
Dupe of #26

**Closed by DaveRandom** 2017-03-03 12:32 UTC
